### ISSUE TITLE
Add a way to share your score with friends

### ISSUE THREAD

**Issue by thuiop** [accuracity/accuracity#1]
Something I find a must with games like this is the ability to share your score with your friends, especially since you have a daily mode. This can be as simple as generating a string representing a message like "I scored XXXX on today's Accuracity ! https://accura.city/" and copying it to clipboard.

**Comment by accuracity** [comment]
This is a good idea, I will implement it!

**Comment by accuracity** [comment]
Exemple de texte : Aujourd'hui j'ai fait 1186 – Moyenne 593 à Accuracity ! – https://accura.city/
