### ISSUE TITLE
Broken link on main page

### ISSUE THREAD

**Issue by tbrintet** [accuracity/accuracity#6]
Hello !

It seems like the link to the source of the data set (Jeu de données [DREAL Poitou-Charentes]) leads to a 404.

**Comment by accuracity** [comment]
Thank you, I will fix the link

**Comment by accuracity** [comment]
The link to data.gouv.fr has been removed, however the following link could be used instead: https://datastory-datactivist.opendatasoft.com/explore/dataset/dreal/information/

**Comment by tbrintet** [comment]
Yes this is a good alternative.
It is pretty strange, it looks like the original data vanished and got deleted from data.gouv.fr.
